import imageSizes from './data/imageSizes.json' with {type:'json'};
import siteContent from './data/siteContent.json' with {type:'json'};
export const whatsapp=`https://wa.me/${siteContent.integrations.whatsapp.number}`;
export const wa=(message='Olá, Hosana! Conheci seu site e gostaria de informações sobre os tratamentos e agendamento.')=>`${whatsapp}?text=${encodeURIComponent(message)}`;
const arrow='<span aria-hidden="true">↗</span>';
export const button=(label,href,cls='')=>`<a class="button ${cls}" href="${href}" ${href.startsWith('https')?'target="_blank" rel="noopener noreferrer"':''}>${label}${arrow}</a>`;
export const picture=(key,alt,cls='',eager=false)=>{const width=imageSizes[key]?.width||(key==='hosana'?1078:key==='equipe'?1280:1254);const height=imageSizes[key]?.height||(key==='hosana'?1459:key==='equipe'?1215:1254);return `<img class="${cls}" src="/assets/${key}-1280.webp" srcset="/assets/${key}-640.webp 640w, /assets/${key}-1280.webp ${width}w" sizes="${cls==='hero-image'?'100vw':'(max-width: 640px) 100vw, 60vw'}" alt="${alt}" width="${width}" height="${height}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;};
export function head(title='Hosana Amaral | Estética Avançada') {return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f7f4f0"><title>${title}</title><meta name="description" content="Estética avançada com atenção aos detalhes e uma experiência pensada para você. Conheça Hosana Amaral e converse com a equipe."><meta property="og:title" content="${title}"><meta property="og:description" content="Beleza em movimento. Cuidado em cada detalhe."><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600&family=Manrope:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css"></head>`;}
export function render(c) {
const slides=[{title:c.hero.headline,eyebrow:c.hero.eyebrow,text:c.hero.description,key:'hosana',alt:'Hosana Amaral em seu espaço de atendimento',cta:'Conhecer os tratamentos',href:'#tratamentos'},...c.categoryHighlights.map((s,i)=>({title:s.headline,eyebrow:s.category,text:s.description,key:i?'equipe':'atendimento',alt:i?'Equipe de Hosana Amaral no espaço de estética':'Hosana Amaral durante atendimento facial',cta:s.cta,href:'#tratamentos',filter:i?'Corporal':'Facial'})),{title:c.earlyConversionBlock.headline,eyebrow:c.earlyConversionBlock.eyebrow,text:c.earlyConversionBlock.description,key:'premios',alt:'Hosana Amaral segurando seus certificados',cta:c.earlyConversionBlock.cta.label,href:wa()}];
return `${head()}<body><a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="header"><a class="brand" href="#inicio" aria-label="Hosana Amaral Estética Avançada — início">Hosana Amaral<small>ESTÉTICA AVANÇADA</small></a><nav class="desktop-nav" aria-label="Navegação principal">${c.navigation.items.map(x=>`<a href="${x.target}">${x.label}</a>`).join('')}</nav>${button('Agendar avaliação',wa(),'header-cta')}<button class="menu-toggle" aria-label="Abrir menu" aria-haspopup="dialog">☰</button></header><dialog class="mobile-menu" aria-label="Menu de navegação"><button class="close-menu icon-button" aria-label="Fechar menu">×</button><a class="brand" href="#inicio">Hosana Amaral<small>ESTÉTICA AVANÇADA</small></a><nav>${c.navigation.items.map(x=>`<a href="${x.target}">${x.label}</a>`).join('')}</nav>${button('Agendar avaliação',wa())}</dialog><main id="conteudo"><section class="hero" id="inicio" aria-label="Destaques Hosana Amaral" aria-roledescription="carrossel">${slides.map((s,i)=>`<article class="hero-slide ${i===0?'active':''}" ${i?'inert aria-hidden="true"':''} aria-roledescription="slide" aria-label="${i+1} de 4">${picture(s.key,s.alt,'hero-image',i===0)}<div class="photo-shade"></div><div class="hero-copy container"><p class="eyebrow">${s.eyebrow}</p><${i===0?'h1':'h2'}>${s.title}</${i===0?'h1':'h2'}><p class="intro">${s.text}</p><a class="button light" href="${s.href}" ${s.filter?`data-filter-link="${s.filter}"`:''} ${s.href.startsWith('https')?'target="_blank" rel="noopener noreferrer"':''}>${s.cta}${arrow}</a></div></article>`).join('')}<div class="hero-controls container"><a class="discover" href="#manifesto">↓ <span>DESCUBRA MAIS</span></a><div class="slide-select" aria-label="Selecionar slide">${slides.map((s,i)=>`<button class="slide-dot ${i===0?'active':''}" aria-label="Mostrar slide ${i+1} de 4" aria-pressed="${i===0}"><span>0${i+1}</span><i></i></button>`).join('')}</div><div class="hero-arrows"><span class="slide-count" aria-live="off">01 / 04</span><button class="icon-button prev" aria-label="Slide anterior">←</button><button class="icon-button next" aria-label="Próximo slide">→</button><button class="icon-button play" aria-label="Pausar apresentação">Ⅱ</button></div></div><p id="slide-status" class="sr-only" role="status"></p></section><section id="manifesto" class="manifesto section container"><div class="manifesto-copy"><p class="eyebrow">${c.discoverySection.featured.eyebrow}</p><h2>${c.discoverySection.featured.headline}</h2><p>${c.discoverySection.featured.description}</p>${button('Conheça nossa história','#sobre','text-link')}</div><figure>${picture('hosana','Hosana Amaral em seu espaço de atendimento')}<figcaption>HOSANA AMARAL · ESTÉTICA AVANÇADA</figcaption></figure></section><!-- SECTIONS --></main><script type="module" src="/app.js"></script></body></html>`;
}
